package Database;

/* CVS $Id: $ */

import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:/C:/Program%20Files/Protege_3.4.1/schemagen-temp.owl 
 * @author Auto-generated by schemagen on 17 Oct 2009 09:34 
 */
public class Message {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.owl-ontologies.com/Ontology1254153498.owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty hasBody = m_model.createObjectProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#hasBody" );
    
    public static final ObjectProperty hasHeader = m_model.createObjectProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#hasHeader" );
    
    public static final ObjectProperty hasMessageData = m_model.createObjectProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#hasMessageData" );
    
    public static final ObjectProperty hasSequenceNumber = m_model.createObjectProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#hasSequenceNumber" );
    
    public static final DatatypeProperty action = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#action" );
    
    public static final DatatypeProperty content = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#content" );
    
    public static final DatatypeProperty conversationId = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#conversationId" );
    
    public static final DatatypeProperty from = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#from" );
    
    public static final DatatypeProperty language = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#language" );
    
    public static final DatatypeProperty messageId = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#messageId" );
    
    public static final DatatypeProperty ontology = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#ontology" );
    
    /** <p>Contains the message identifier from the original MessageId that “this” message 
     *  is in response to</p>
     */
    public static final DatatypeProperty refToMessageId = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#refToMessageId" );
    
    public static final DatatypeProperty service = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#service" );
    
    public static final DatatypeProperty status = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#status" );
    
    public static final DatatypeProperty timeToLive = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#timeToLive" );
    
    public static final DatatypeProperty timestamp = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#timestamp" );
    
    public static final DatatypeProperty to = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254153498.owl#to" );
    
    public static final OntClass Body = m_model.createClass( "http://www.owl-ontologies.com/Ontology1254153498.owl#Body" );
    
    public static final OntClass Header = m_model.createClass( "http://www.owl-ontologies.com/Ontology1254153498.owl#Header" );
    
    public static final OntClass Message = m_model.createClass( "http://www.owl-ontologies.com/Ontology1254153498.owl#Message" );
    
    /** <p></p> */
    public static final OntClass MessageData = m_model.createClass( "http://www.owl-ontologies.com/Ontology1254153498.owl#MessageData" );
    
    public static final OntClass SequenceNumber = m_model.createClass( "http://www.owl-ontologies.com/Ontology1254153498.owl#SequenceNumber" );
    
}

