/* CVS $Id: $ */
package com.ptit.travel.jane.agent; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:/C:/Program%20Files/Protege_3.4/schemagen-temp.owl 
 * @author Auto-generated by schemagen on 09 Jan 2010 22:38 
 */
public class Agent {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.owl-ontologies.com/Ontology1254907557.owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final DatatypeProperty address = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254907557.owl#address" );
    
    public static final DatatypeProperty discription = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254907557.owl#discription" );
    
    /** <p>the same to id in Member ontology</p> */
    public static final DatatypeProperty id = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254907557.owl#id" );
    
    public static final DatatypeProperty owner = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254907557.owl#owner" );
    
    public static final DatatypeProperty state = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254907557.owl#state" );
    
    public static final DatatypeProperty type = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Ontology1254907557.owl#type" );
    
    public static final OntClass Agent = m_model.createClass( "http://www.owl-ontologies.com/Ontology1254907557.owl#Agent" );
    
    public static final Individual Agent_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Ontology1254907557.owl#Agent_1", Agent );
    
    public static final Individual Agent_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Ontology1254907557.owl#Agent_2", Agent );
    
}
