/* CVS $Id: $ */
package model; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*; 
/**
 * Vocabulary definitions from file:/C:/Program%20Files/Protege_3.3.1/schemagen-temp.owl 
 * @author Auto-generated by schemagen on 06 May 2009 14:18 
 */
public class Sharing {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://eduportal.vn/chiase/myontology#";
    public static final String RDF = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
    public static final String RDFS = "http://www.w3.org/2000/01/rdf-schema#";
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty BanGhiCoThuocTinh = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#BanGhiCoThuocTinh" );
    
    public static final ObjectProperty TapMauCuaBanGhi = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#TapMauCuaBanGhi" );
    
    public static final ObjectProperty BanGhiCuaTaiLieu = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#BanGhiCuaTaiLieu" );
    
    public static final ObjectProperty KetQuaLaTaiLieu = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#KetQuaLaTaiLieu" );
    
    public static final ObjectProperty BanGhiCoTapMau = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#BanGhiCoTapMau" );
    
    public static final ObjectProperty LinhVucCoThuocTinh = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#LinhVucCoThuocTinh" );
    
    public static final ObjectProperty ThuocLinhVuc = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#ThuocLinhVuc" );
    
    public static final ObjectProperty CoTacPham = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#CoTacPham" );
    
    public static final ObjectProperty ThuocTinhCoBanGhi = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#ThuocTinhCoBanGhi" );
    
    public static final ObjectProperty CongTac = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#CongTac" );
    
    public static final ObjectProperty PhuongThucCoBanGhi = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#PhuongThucCoBanGhi" );
    
    public static final ObjectProperty ThuocTinhThuocLinhVuc = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#ThuocTinhThuocLinhVuc" );
    
    public static final ObjectProperty PhuongThucThuocTaiLieu = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#PhuongThucThuocTaiLieu" );
    
    public static final ObjectProperty LienKet = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#LienKet" );
    
    public static final ObjectProperty BanGhiCoPhuongThuc = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#BanGhiCoPhuongThuc" );
    
    public static final ObjectProperty KetQuaCuaTapMau = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#KetQuaCuaTapMau" );
    
    public static final ObjectProperty CoTaiLieu = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#CoTaiLieu" );
    
    public static final ObjectProperty CoTacGia = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#CoTacGia" );
    
    public static final ObjectProperty TaiLieuCobanGhi = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#TaiLieuCobanGhi" );
    
    public static final ObjectProperty DaHoTro = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#DaHoTro" );
    
    public static final ObjectProperty TapMauCoKetQua = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#TapMauCoKetQua" );
    
    public static final ObjectProperty TaiLieuCoPhuongThuc = m_model.createObjectProperty( "http://eduportal.vn/chiase/myontology#TaiLieuCoPhuongThuc" );
    
    public static final DatatypeProperty DinhDang = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#DinhDang" );
    
    public static final DatatypeProperty AnhMinhHoa = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#AnhMinhHoa" );
    
    public static final DatatypeProperty BanGhiCoTheLoai = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#BanGhiCoTheLoai" );
    
    public static final DatatypeProperty MoTaNoiDung = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#MoTaNoiDung" );
    
    public static final DatatypeProperty TenGoi = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#TenGoi" );
    
    public static final DatatypeProperty Email = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#Email" );
    
    public static final DatatypeProperty BanQuyen = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#BanQuyen" );
    
    public static final DatatypeProperty NgonNgu = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#NgonNgu" );
    
    public static final DatatypeProperty NoiChua = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#NoiChua" );
    
    public static final DatatypeProperty TimDung = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#TimDung" );
    
    public static final DatatypeProperty NhanDe = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#NhanDe" );
    
    public static final DatatypeProperty SoDienThoai = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#SoDienThoai" );
    
    public static final DatatypeProperty BanGhiCoNhanDe = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#BanGhiCoNhanDe" );
    
    public static final DatatypeProperty DeMuc = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#DeMuc" );
    
    public static final DatatypeProperty NhaXuatBan = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#NhaXuatBan" );
    
    public static final DatatypeProperty BanGhiCoNhaXuatBan = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#BanGhiCoNhaXuatBan" );
    
    public static final DatatypeProperty SoTrang = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#SoTrang" );
    
    public static final DatatypeProperty NguonGoc = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#NguonGoc" );
    
    public static final DatatypeProperty NgayThang = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#NgayThang" );
    
    public static final DatatypeProperty BanGhiCoTacGia = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#BanGhiCoTacGia" );
    
    public static final DatatypeProperty NickName = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#NickName" );
    
    public static final DatatypeProperty TuKhoa = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#TuKhoa" );
    
    public static final DatatypeProperty BanGhiCoChuyenNganh = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#BanGhiCoChuyenNganh" );
    
    public static final DatatypeProperty TotalDownload = m_model.createDatatypeProperty( "http://eduportal.vn/chiase/myontology#TotalDownload" );
    
    /** <p>Con ???ng c?a ??ng và nhân dân ?ã ch?n</p> */
    public static final OntClass GiaoDucChinhTri = m_model.createClass( "http://eduportal.vn/chiase/myontology#GiaoDucChinhTri" );
    
    /** <p>Giáo trình gi?ng d?y chu?n c?a các tr??ng</p> */
    public static final OntClass GiaoTrinh = m_model.createClass( "http://eduportal.vn/chiase/myontology#GiaoTrinh" );
    
    /** <p>Công ngh? c?a t??ng lai</p> */
    public static final OntClass CongNgheSinhHoc = m_model.createClass( "http://eduportal.vn/chiase/myontology#CongNgheSinhHoc" );
    
    /** <p>Hay quá, th? kìa</p> */
    public static final OntClass ThoCa = m_model.createClass( "http://eduportal.vn/chiase/myontology#ThoCa" );
    
    /** <p>Kh? n?ng có th? làm ???c</p> */
    public static final OntClass PhuongThuc = m_model.createClass( "http://eduportal.vn/chiase/myontology#PhuongThuc" );
    
    public static final OntClass NguoiDung = m_model.createClass( "http://eduportal.vn/chiase/myontology#NguoiDung" );
    
    /** <p>Phát tri?n h? th?ng vi?n thông</p> */
    public static final OntClass DienTuVienThong = m_model.createClass( "http://eduportal.vn/chiase/myontology#DienTuVienThong" );
    
    public static final OntClass QuanTri = m_model.createClass( "http://eduportal.vn/chiase/myontology#QuanTri" );
    
    public static final OntClass ConNguoi = m_model.createClass( "http://eduportal.vn/chiase/myontology#ConNguoi" );
    
    public static final OntClass TacGia = m_model.createClass( "http://eduportal.vn/chiase/myontology#TacGia" );
    
    public static final OntClass ThanhVien = m_model.createClass( "http://eduportal.vn/chiase/myontology#ThanhVien" );
    
    /** <p>Cái này thì ch?u</p> */
    public static final OntClass TieuThuyet = m_model.createClass( "http://eduportal.vn/chiase/myontology#TieuThuyet" );
    
    /** <p>K?t qu? nghiên c?u, ?? án, lu?n v?n...</p> */
    public static final OntClass BaoCao = m_model.createClass( "http://eduportal.vn/chiase/myontology#BaoCao" );
    
    public static final OntClass TinhChat = m_model.createClass( "http://eduportal.vn/chiase/myontology#TinhChat" );
    
    /** <p>Vâng, ?ây là truy?n ??y ?</p> */
    public static final OntClass Truyen = m_model.createClass( "http://eduportal.vn/chiase/myontology#Truyen" );
    
    /** <p>N?n t?ng phát tri?n kinh t?</p> */
    public static final OntClass KhoaHocKyThuat = m_model.createClass( "http://eduportal.vn/chiase/myontology#KhoaHocKyThuat" );
    
    /** <p>H? tr? cho tri th?c và h?c h?i</p> */
    public static final OntClass ThuNhan = m_model.createClass( "http://eduportal.vn/chiase/myontology#ThuNhan" );
    
    public static final OntClass LinhVuc = m_model.createClass( "http://eduportal.vn/chiase/myontology#LinhVuc" );
    
    /** <p>???ng l?i làm ?n</p> */
    public static final OntClass KinhTeQuanLy = m_model.createClass( "http://eduportal.vn/chiase/myontology#KinhTeQuanLy" );
    
    public static final OntClass Khach = m_model.createClass( "http://eduportal.vn/chiase/myontology#Khach" );
    
    /** <p>?ây là m?t ngành công ngh? quan tr?ng và c?n ???c ?u tiên phát tri?n</p> */
    public static final OntClass CongNgheThongTin = m_model.createClass( "http://eduportal.vn/chiase/myontology#CongNgheThongTin" );
    
    /** <p>Tài li?u chu?n c?a b? giáo d?c</p> */
    public static final OntClass SachGiaoKhoa = m_model.createClass( "http://eduportal.vn/chiase/myontology#SachGiaoKhoa" );
    
    public static final OntClass TaiNguyen = m_model.createClass( "http://eduportal.vn/chiase/myontology#TaiNguyen" );
    
    public static final OntClass TaiLieu = m_model.createClass( "http://eduportal.vn/chiase/myontology#TaiLieu" );
    
    /** <p>Phát tri?n con ng??i toàn di?n, kh?e m?nh</p> */
    public static final OntClass GiaoDucTheChat = m_model.createClass( "http://eduportal.vn/chiase/myontology#GiaoDucTheChat" );
    
    /** <p>K?t qu? suy di?n ???c ?úc rút</p> */
    public static final OntClass TapMau = m_model.createClass( "http://eduportal.vn/chiase/myontology#TapMau" );
    
    /** <p>Cái này thì tùy</p> */
    public static final OntClass LinhVucKhac = m_model.createClass( "http://eduportal.vn/chiase/myontology#LinhVucKhac" );
    
    /** <p>Tài li?u tham kh?o cho sinh viên , h?c sinh và ....</p> */
    public static final OntClass SachThamKhao = m_model.createClass( "http://eduportal.vn/chiase/myontology#SachThamKhao" );
    
    /** <p>Môi tr??ng b?n v?ng</p> */
    public static final OntClass KhoaHocMoiTruong = m_model.createClass( "http://eduportal.vn/chiase/myontology#KhoaHocMoiTruong" );
    
    /** <p>K?t qu? c?a các quá trình suy di?n</p> */
    public static final OntClass KetQua = m_model.createClass( "http://eduportal.vn/chiase/myontology#KetQua" );
    
    /** <p>?ây là l?p ch?a ??c ?i?m c?a các ??i t??ng</p> */
    public static final OntClass ThuocTinh = m_model.createClass( "http://eduportal.vn/chiase/myontology#ThuocTinh" );
    
    /** <p>Thúc ??y phát tri?n các ngành k? thu?t</p> */
    public static final OntClass KhoaHocTuNhien = m_model.createClass( "http://eduportal.vn/chiase/myontology#KhoaHocTuNhien" );
    
    /** <p>Phát tri?n tâm h?n ta trong sáng và phong phú</p> */
    public static final OntClass KhoaHocXaHoi = m_model.createClass( "http://eduportal.vn/chiase/myontology#KhoaHocXaHoi" );
    
    /** <p>Phát tri?n b?n v?ng v? kinh t?, phát tri?n nông lâm ng? nghi?p</p> */
    public static final OntClass NongLamNguNghiep = m_model.createClass( "http://eduportal.vn/chiase/myontology#NongLamNguNghiep" );
    
    public static final OntClass CongTacVien = m_model.createClass( "http://eduportal.vn/chiase/myontology#CongTacVien" );
    
    /** <p>Nh?ng ng??i có công l?n nh?t trong vi?c xây d?ng tài liêu</p> */
    public static final OntClass TacGiaChinh = m_model.createClass( "http://eduportal.vn/chiase/myontology#TacGiaChinh" );
    
    /** <p>Nghiên c?u khoa h?c</p> */
    public static final OntClass TaiLieuNghienCuu = m_model.createClass( "http://eduportal.vn/chiase/myontology#TaiLieuNghienCuu" );
    
    /** <p>Ph?n so?n th?o gi?ng d?y c?a giáo viên</p> */
    public static final OntClass BaiGiang = m_model.createClass( "http://eduportal.vn/chiase/myontology#BaiGiang" );
    
    /** <p>Các b?n ghi thông tin</p> */
    public static final OntClass BanGhi = m_model.createClass( "http://eduportal.vn/chiase/myontology#BanGhi" );
    
    public static final Individual ThanhVien_1 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#ThanhVien_1", ThanhVien );
    
    public static final Individual Khach_1 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#Khach_1", Khach );
    
    public static final Individual PhuongThuc_1 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#PhuongThuc_1", PhuongThuc );
    
    public static final Individual CongTacVien_1 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#CongTacVien_1", CongTacVien );
    
    public static final Individual QuanTri_1 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#QuanTri_1", QuanTri );
    
    public static final Individual ThuocTinh_2 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#ThuocTinh_2", ThuocTinh );
    
    public static final Individual GiaoTrinh_1 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#GiaoTrinh_1", GiaoTrinh );
    
    public static final Individual CongTacVien_2 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#CongTacVien_2", CongTacVien );
    
    public static final Individual GiaoTrinh_2 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#GiaoTrinh_2", GiaoTrinh );
    
    public static final Individual CongNgheThongTin_2 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#CongNgheThongTin_2", CongNgheThongTin );
    
    public static final Individual TacGiaChinh_2 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#TacGiaChinh_2", TacGiaChinh );
    
    public static final Individual CongNgheThongTin_1 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#CongNgheThongTin_1", CongNgheThongTin );
    
    public static final Individual TacGiaChinh_1 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#TacGiaChinh_1", TacGiaChinh );
    
    public static final Individual ThuocTinh_1 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#ThuocTinh_1", ThuocTinh );
    
    public static final Individual CongNgheThongTin_4 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#CongNgheThongTin_4", CongNgheThongTin );
    
    public static final Individual CongNgheThongTin_3 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#CongNgheThongTin_3", CongNgheThongTin );
    
    public static final Individual CongNgheThongTin_6 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#CongNgheThongTin_6", CongNgheThongTin );
    
    public static final Individual CongNgheThongTin_5 = m_model.createIndividual( "http://eduportal.vn/chiase/myontology#CongNgheThongTin_5", CongNgheThongTin );
    
}
