/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ptit.edu.travel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import com.ptit.edu.travel.struts.form.hotel.BookRoomInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-23-2009
 * 
 * XDoclet definition:
 * @struts.action path="/bookRoomInfo" name="bookRoomInfoForm" input="/form/bookRoomInfo.jsp" parameter="action" scope="request" validate="true"
 * @struts.action-forward name="prepareBookHotel" path="hotel.book"
 * @struts.action-forward name="formatError" path="format.error"
 */
public class BookRoomInfoAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward searchRoom(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BookRoomInfoForm bookRoomInfoForm = (BookRoomInfoForm) form;// TODO Auto-generated method stub
		
		// get input parameters 
		String destination = request.getParameter("destination");
		String beginDate = request.getParameter("beginDate");
		String endDate = request.getParameter("endDate");
		String numberStar = request.getParameter("numberStar");
		String price = request.getParameter("price");
		
		// create message
		
		return null;
	}
}