/* CVS $Id: $ */
package com.ptit.travel.jane.Flight; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:/C:/Program%20Files/Protege_3.4/schemagen-temp.owl 
 * @author Auto-generated by schemagen on 02 Jan 2010 10:40 
 */
public class Flight {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.owl-ontologies.com/Flight.owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty hasAdress = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasAdress" );
    
    public static final ObjectProperty hasAgentFlightInfo = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasAgentFlightInfo" );
    
    public static final ObjectProperty hasAirplane = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasAirplane" );
    
    public static final ObjectProperty hasArrivalAirport = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasArrivalAirport" );
    
    public static final ObjectProperty hasArrivalDateTime = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasArrivalDateTime" );
    
    public static final ObjectProperty hasCustomer = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasCustomer" );
    
    public static final ObjectProperty hasDepartureAirport = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasDepartureAirport" );
    
    public static final ObjectProperty hasDepartureDateTime = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasDepartureDateTime" );
    
    public static final ObjectProperty hasFlight = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasFlight" );
    
    public static final ObjectProperty hasFlightAgent = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasFlightAgent" );
    
    public static final ObjectProperty hasFlightAgentInfo = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasFlightAgentInfo" );
    
    public static final ObjectProperty hasFlightManager = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasFlightManager" );
    
    public static final ObjectProperty hasPrice = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasPrice" );
    
    public static final ObjectProperty hasSecurityCode = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasSecurityCode" );
    
    /** <p>Hang hang khong</p> */
    public static final DatatypeProperty airline = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#airline" );
    
    /** <p>Hang san xuat may bay (Airbus, Boeing)</p> */
    public static final DatatypeProperty airplaneMaker = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#airplaneMaker" );
    
    public static final DatatypeProperty airplaneType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#airplaneType" );
    
    public static final DatatypeProperty airportName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#airportName" );
    
    public static final DatatypeProperty arrivalAirportCity = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#arrivalAirportCity" );
    
    public static final DatatypeProperty bookNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#bookNumber" );
    
    public static final DatatypeProperty bookdate = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#bookdate" );
    
    public static final DatatypeProperty city = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#city" );
    
    /** <p>Ma hop dong</p> */
    public static final DatatypeProperty contractCode = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#contractCode" );
    
    public static final DatatypeProperty country = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#country" );
    
    /** <p>Ngay cu the</p> */
    public static final DatatypeProperty date = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#date" );
    
    public static final DatatypeProperty departureAirportCity = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#departureAirportCity" );
    
    public static final DatatypeProperty description = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#description" );
    
    public static final DatatypeProperty email = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#email" );
    
    public static final DatatypeProperty fax = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#fax" );
    
    public static final DatatypeProperty flightAgentName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#flightAgentName" );
    
    /** <p>Loai ve may bay</p> */
    public static final DatatypeProperty flightClass = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#flightClass" );
    
    public static final DatatypeProperty flightInformation = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#flightInformation" );
    
    /** <p>Ma so chuyen bay</p> */
    public static final DatatypeProperty flightNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#flightNumber" );
    
    public static final DatatypeProperty fullName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#fullName" );
    
    public static final DatatypeProperty gender = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#gender" );
    
    public static final DatatypeProperty id = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#id" );
    
    public static final DatatypeProperty introduce = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#introduce" );
    
    /** <p>Thong bao kem theo</p> */
    public static final DatatypeProperty notification = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#notification" );
    
    public static final DatatypeProperty password = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#password" );
    
    public static final DatatypeProperty phoneNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#phoneNumber" );
    
    public static final DatatypeProperty price = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#price" );
    
    public static final DatatypeProperty priceUnit = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#priceUnit" );
    
    public static final DatatypeProperty specificAdress = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#specificAdress" );
    
    /** <p>Thoi gian cu the trong ngay</p> */
    public static final DatatypeProperty time = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#time" );
    
    public static final DatatypeProperty totalBookNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#totalBookNumber" );
    
    public static final DatatypeProperty totalNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#totalNumber" );
    
    public static final DatatypeProperty username = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#username" );
    
    public static final OntClass Adress = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Adress" );
    
    public static final OntClass Airplane = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Airplane" );
    
    public static final OntClass Airport = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Airport" );
    
    public static final OntClass Customer = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Customer" );
    
    /** <p></p> */
    public static final OntClass Flight = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Flight" );
    
    public static final OntClass FlightAgent = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#FlightAgent" );
    
    public static final OntClass FlightAgentInfo = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#FlightAgentInfo" );
    
    public static final OntClass FlightBookContract = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#FlightBookContract" );
    
    public static final OntClass FlightManager = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#FlightManager" );
    
    public static final OntClass Msg_FlightAvailRQ = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_FlightAvailRQ" );
    
    public static final OntClass Msg_FlightAvailRS = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_FlightAvailRS" );
    
    public static final OntClass Msg_FlightBookChangeConfirmRQ = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_FlightBookChangeConfirmRQ" );
    
    public static final OntClass Msg_FlightBookChangeRQ = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_FlightBookChangeRQ" );
    
    public static final OntClass Msg_FlightBookChangeRS = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_FlightBookChangeRS" );
    
    public static final OntClass Msg_FlightBookRQ = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_FlightBookRQ" );
    
    public static final OntClass Msg_FlightBookRS = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_FlightBookRS" );
    
    public static final OntClass Msg_FlightRegisterRQ = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_FlightRegisterRQ" );
    
    public static final OntClass Msg_PublishFlightRQ = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_PublishFlightRQ" );
    
    public static final OntClass PointOfTime = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#PointOfTime" );
    
    public static final OntClass Price = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Price" );
    
    public static final OntClass SecurityCode = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#SecurityCode" );
    
    public static final Individual AChau = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#AChau", FlightAgentInfo );
    
    public static final Individual ANZ = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#ANZ", FlightAgentInfo );
    
    public static final Individual A_10 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#A_10", PointOfTime );
    
    public static final Individual A_11_10 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#A_11_10", PointOfTime );
    
    public static final Individual A_12 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#A_12", PointOfTime );
    
    public static final Individual A_13 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#A_13", PointOfTime );
    
    public static final Individual A_14_30 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#A_14_30", PointOfTime );
    
    public static final Individual A_15 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#A_15", PointOfTime );
    
    public static final Individual A_15_10 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#A_15_10", PointOfTime );
    
    public static final Individual A_16_30 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#A_16_30", PointOfTime );
    
    public static final Individual A_17 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#A_17", PointOfTime );
    
    public static final Individual A_18_20 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#A_18_20", PointOfTime );
    
    public static final Individual A_19 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#A_19", PointOfTime );
    
    public static final Individual A_21 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#A_21", PointOfTime );
    
    public static final Individual Airbus321 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#Airbus321", Airplane );
    
    public static final Individual Airbus_A320 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#Airbus_A320", Airplane );
    
    public static final Individual BL791_E1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL791_E1", Flight );
    
    public static final Individual BL791_E2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL791_E2", Flight );
    
    public static final Individual BL791_E3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL791_E3", Flight );
    
    public static final Individual BL791_E4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL791_E4", Flight );
    
    public static final Individual BL791_E5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL791_E5", Flight );
    
    public static final Individual BL797_E1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL797_E1", Flight );
    
    public static final Individual BL797_E2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL797_E2", Flight );
    
    public static final Individual BL797_E3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL797_E3", Flight );
    
    public static final Individual BL797_E4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL797_E4", Flight );
    
    public static final Individual BL797_E5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL797_E5", Flight );
    
    public static final Individual BL799_E1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL799_E1", Flight );
    
    public static final Individual BL799_E2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL799_E2", Flight );
    
    public static final Individual BL799_E3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL799_E3", Flight );
    
    public static final Individual BL799_E4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL799_E4", Flight );
    
    public static final Individual BL799_E5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL799_E5", Flight );
    
    public static final Individual BL805_E1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL805_E1", Flight );
    
    public static final Individual BL805_E2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL805_E2", Flight );
    
    public static final Individual BL_805_E3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL_805_E3", Flight );
    
    public static final Individual BL_805_E4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL_805_E4", Flight );
    
    public static final Individual BL_805_E5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#BL_805_E5", Flight );
    
    public static final Individual Boeing737 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#Boeing737", Airplane );
    
    public static final Individual Boeing_777 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#Boeing_777", Airplane );
    
    public static final Individual CXR = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#CXR", Airport );
    
    public static final Individual ConDao = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#ConDao", Airport );
    
    public static final Individual DAD = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#DAD", Airport );
    
    public static final Individual DIN = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#DIN", Airport );
    
    public static final Individual DLI = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#DLI", Airport );
    
    public static final Individual D_10_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_10_1", PointOfTime );
    
    public static final Individual D_10_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_10_2", PointOfTime );
    
    public static final Individual D_10_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_10_3", PointOfTime );
    
    public static final Individual D_10_4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_10_4", PointOfTime );
    
    public static final Individual D_10_5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_10_5", PointOfTime );
    
    public static final Individual D_11_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_11_1", PointOfTime );
    
    public static final Individual D_11_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_11_2", PointOfTime );
    
    public static final Individual D_11_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_11_3", PointOfTime );
    
    public static final Individual D_11_4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_11_4", PointOfTime );
    
    public static final Individual D_11_5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_11_5", PointOfTime );
    
    public static final Individual D_13_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_13_1", PointOfTime );
    
    public static final Individual D_13_10_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_13_10_1", PointOfTime );
    
    public static final Individual D_13_10_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_13_10_2", PointOfTime );
    
    public static final Individual D_13_10_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_13_10_3", PointOfTime );
    
    public static final Individual D_13_10_4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_13_10_4", PointOfTime );
    
    public static final Individual D_13_10_5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_13_10_5", PointOfTime );
    
    public static final Individual D_13_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_13_2", PointOfTime );
    
    public static final Individual D_13_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_13_3", PointOfTime );
    
    public static final Individual D_13_4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_13_4", PointOfTime );
    
    public static final Individual D_13_5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_13_5", PointOfTime );
    
    public static final Individual D_14_30_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_14_30_1", PointOfTime );
    
    public static final Individual D_14_30_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_14_30_2", PointOfTime );
    
    public static final Individual D_14_30_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_14_30_3", PointOfTime );
    
    public static final Individual D_14_30_4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_14_30_4", PointOfTime );
    
    public static final Individual D_14_30_5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_14_30_5", PointOfTime );
    
    public static final Individual D_15_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_15_1", PointOfTime );
    
    public static final Individual D_15_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_15_2", PointOfTime );
    
    public static final Individual D_15_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_15_3", PointOfTime );
    
    public static final Individual D_15_4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_15_4", PointOfTime );
    
    public static final Individual D_15_5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_15_5", PointOfTime );
    
    public static final Individual D_16_20_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_16_20_1", PointOfTime );
    
    public static final Individual D_16_20_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_16_20_2", PointOfTime );
    
    public static final Individual D_16_20_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_16_20_3", PointOfTime );
    
    public static final Individual D_16_20_4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_16_20_4", PointOfTime );
    
    public static final Individual D_16_20_5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_16_20_5", PointOfTime );
    
    public static final Individual D_17_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_17_1", PointOfTime );
    
    public static final Individual D_17_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_17_2", PointOfTime );
    
    public static final Individual D_17_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_17_3", PointOfTime );
    
    public static final Individual D_17_4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_17_4", PointOfTime );
    
    public static final Individual D_17_5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_17_5", PointOfTime );
    
    public static final Individual D_19_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_19_1", PointOfTime );
    
    public static final Individual D_19_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_19_2", PointOfTime );
    
    public static final Individual D_19_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_19_3", PointOfTime );
    
    public static final Individual D_19_4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_19_4", PointOfTime );
    
    public static final Individual D_19_5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_19_5", PointOfTime );
    
    public static final Individual D_8_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_8_1", PointOfTime );
    
    public static final Individual D_8_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_8_2", PointOfTime );
    
    public static final Individual D_8_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_8_3", PointOfTime );
    
    public static final Individual D_8_4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_8_4", PointOfTime );
    
    public static final Individual D_8_5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_8_5", PointOfTime );
    
    public static final Individual D_9_10_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_9_10_1", PointOfTime );
    
    public static final Individual D_9_10_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_9_10_2", PointOfTime );
    
    public static final Individual D_9_10_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_9_10_3", PointOfTime );
    
    public static final Individual D_9_10_4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_9_10_4", PointOfTime );
    
    public static final Individual D_9_10_5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_9_10_5", PointOfTime );
    
    public static final Individual Fokker70 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#Fokker70", Airplane );
    
    public static final Individual GiaiPhong = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#GiaiPhong", Adress );
    
    public static final Individual GiaiPhong_FlightAgent = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#GiaiPhong_FlightAgent", FlightAgent );
    
    public static final Individual HAN = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#HAN", Airport );
    
    public static final Individual HPH = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#HPH", Airport );
    
    public static final Individual HUI = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#HUI", Airport );
    
    public static final Individual M_BL791_E1_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL791_E1_1", FlightManager );
    
    public static final Individual M_BL791_E1_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL791_E1_2", FlightManager );
    
    public static final Individual M_BL791_E1_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL791_E1_3", FlightManager );
    
    public static final Individual M_BL791_E2_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL791_E2_1", FlightManager );
    
    public static final Individual M_BL791_E2_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL791_E2_2", FlightManager );
    
    public static final Individual M_BL791_E2_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL791_E2_3", FlightManager );
    
    public static final Individual M_BL791_E3_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL791_E3_1", FlightManager );
    
    public static final Individual M_BL791_E3_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL791_E3_2", FlightManager );
    
    public static final Individual M_BL791_E3_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL791_E3_3", FlightManager );
    
    public static final Individual M_BL791_E4_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL791_E4_1", FlightManager );
    
    public static final Individual M_BL791_E4_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL791_E4_2", FlightManager );
    
    public static final Individual M_BL791_E4_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL791_E4_3", FlightManager );
    
    public static final Individual M_BL791_E5_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL791_E5_1", FlightManager );
    
    public static final Individual M_BL791_E5_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL791_E5_2", FlightManager );
    
    public static final Individual M_BL791_E5_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL791_E5_3", FlightManager );
    
    public static final Individual M_BL797_E1_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL797_E1_1", FlightManager );
    
    public static final Individual M_BL797_E1_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL797_E1_2", FlightManager );
    
    public static final Individual M_BL797_E1_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL797_E1_3", FlightManager );
    
    public static final Individual M_BL797_E2_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL797_E2_1", FlightManager );
    
    public static final Individual M_BL797_E2_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL797_E2_2", FlightManager );
    
    public static final Individual M_BL797_E2_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL797_E2_3", FlightManager );
    
    public static final Individual M_BL797_E3_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL797_E3_1", FlightManager );
    
    public static final Individual M_BL797_E4_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL797_E4_1", FlightManager );
    
    public static final Individual M_BL797_E5_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL797_E5_1", FlightManager );
    
    public static final Individual M_BL799_E1_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL799_E1_1", FlightManager );
    
    public static final Individual M_BL799_E2_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL799_E2_1", FlightManager );
    
    public static final Individual M_BL799_E3_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL799_E3_1", FlightManager );
    
    public static final Individual M_BL799_E3_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL799_E3_2", FlightManager );
    
    public static final Individual M_BL799_E3_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL799_E3_3", FlightManager );
    
    public static final Individual M_BL799_E4_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL799_E4_1", FlightManager );
    
    public static final Individual M_BL799_E4_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL799_E4_2", FlightManager );
    
    public static final Individual M_BL799_E4_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL799_E4_3", FlightManager );
    
    public static final Individual M_BL799_E5_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL799_E5_1", FlightManager );
    
    public static final Individual M_BL799_E5_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL799_E5_2", FlightManager );
    
    public static final Individual M_BL799_E5_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL799_E5_3", FlightManager );
    
    public static final Individual M_BL805_E1_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL805_E1_1", FlightManager );
    
    public static final Individual M_BL805_E1_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL805_E1_2", FlightManager );
    
    public static final Individual M_BL805_E1_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL805_E1_3", FlightManager );
    
    public static final Individual M_BL805_E2_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL805_E2_1", FlightManager );
    
    public static final Individual M_BL805_E2_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL805_E2_2", FlightManager );
    
    public static final Individual M_BL805_E2_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL805_E2_3", FlightManager );
    
    public static final Individual M_BL805_E3_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL805_E3_1", FlightManager );
    
    public static final Individual M_BL805_E3_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL805_E3_2", FlightManager );
    
    public static final Individual M_BL805_E3_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL805_E3_3", FlightManager );
    
    public static final Individual M_BL805_E4_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL805_E4_1", FlightManager );
    
    public static final Individual M_BL805_E4_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL805_E4_2", FlightManager );
    
    public static final Individual M_BL805_E4_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL805_E4_3", FlightManager );
    
    public static final Individual M_BL805_E5_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL805_E5_1", FlightManager );
    
    public static final Individual M_BL805_E5_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL805_E5_2", FlightManager );
    
    public static final Individual M_BL805_E5_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_BL805_E5_3", FlightManager );
    
    public static final Individual M_VN213_B1_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_B1_1", FlightManager );
    
    public static final Individual M_VN213_B1_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_B1_2", FlightManager );
    
    public static final Individual M_VN213_B1_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_B1_3", FlightManager );
    
    public static final Individual M_VN213_B2_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_B2_1", FlightManager );
    
    public static final Individual M_VN213_B2_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_B2_2", FlightManager );
    
    public static final Individual M_VN213_B2_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_B2_3", FlightManager );
    
    public static final Individual M_VN213_B3_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_B3_1", FlightManager );
    
    public static final Individual M_VN213_B3_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_B3_2", FlightManager );
    
    public static final Individual M_VN213_B3_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_B3_3", FlightManager );
    
    public static final Individual M_VN213_B4_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_B4_1", FlightManager );
    
    public static final Individual M_VN213_B4_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_B4_2", FlightManager );
    
    public static final Individual M_VN213_B4_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_B4_3", FlightManager );
    
    public static final Individual M_VN213_B5_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_B5_1", FlightManager );
    
    public static final Individual M_VN213_B5_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_B5_2", FlightManager );
    
    public static final Individual M_VN213_B5_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_B5_3", FlightManager );
    
    public static final Individual M_VN213_E1_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_E1_1", FlightManager );
    
    public static final Individual M_VN213_E1_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_E1_2", FlightManager );
    
    public static final Individual M_VN213_E1_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_E1_3", FlightManager );
    
    public static final Individual M_VN213_E2_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_E2_1", FlightManager );
    
    public static final Individual M_VN213_E3_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_E3_1", FlightManager );
    
    public static final Individual M_VN213_E4_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_E4_1", FlightManager );
    
    public static final Individual M_VN213_E5_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN213_E5_1", FlightManager );
    
    public static final Individual M_VN217_B1_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_B1_1", FlightManager );
    
    public static final Individual M_VN217_B2_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_B2_1", FlightManager );
    
    public static final Individual M_VN217_E1_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_E1_1", FlightManager );
    
    public static final Individual M_VN217_E2_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_E2_1", FlightManager );
    
    public static final Individual M_VN217_E2_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_E2_2", FlightManager );
    
    public static final Individual M_VN217_E2_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_E2_3", FlightManager );
    
    public static final Individual M_VN217_E3_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_E3_1", FlightManager );
    
    public static final Individual M_VN217_E3_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_E3_2", FlightManager );
    
    public static final Individual M_VN217_E3_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_E3_3", FlightManager );
    
    public static final Individual M_VN217_E4_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_E4_1", FlightManager );
    
    public static final Individual M_VN217_E4_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_E4_2", FlightManager );
    
    public static final Individual M_VN217_E4_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_E4_3", FlightManager );
    
    public static final Individual M_VN217_E5_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_E5_1", FlightManager );
    
    public static final Individual M_VN217_E5_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_E5_2", FlightManager );
    
    public static final Individual M_VN217_E5_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_E5_3", FlightManager );
    
    public static final Individual M_VN219_B1_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_B1_1", FlightManager );
    
    public static final Individual M_VN219_B1_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_B1_2", FlightManager );
    
    public static final Individual M_VN219_B1_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_B1_3", FlightManager );
    
    public static final Individual M_VN219_B2_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_B2_1", FlightManager );
    
    public static final Individual M_VN219_B2_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_B2_2", FlightManager );
    
    public static final Individual M_VN219_B2_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_B2_3", FlightManager );
    
    public static final Individual M_VN219_B3_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_B3_1", FlightManager );
    
    public static final Individual M_VN219_B3_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_B3_2", FlightManager );
    
    public static final Individual M_VN219_B3_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_B3_3", FlightManager );
    
    public static final Individual M_VN219_B4_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_B4_1", FlightManager );
    
    public static final Individual M_VN219_B4_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_B4_2", FlightManager );
    
    public static final Individual M_VN219_B4_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_B4_3", FlightManager );
    
    public static final Individual M_VN219_B5_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_B5_1", FlightManager );
    
    public static final Individual M_VN219_B5_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_B5_2", FlightManager );
    
    public static final Individual M_VN219_B5_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_B5_3", FlightManager );
    
    public static final Individual M_VN219_E1_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_E1_1", FlightManager );
    
    public static final Individual M_VN219_E1_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_E1_2", FlightManager );
    
    public static final Individual M_VN219_E1_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_E1_3", FlightManager );
    
    public static final Individual M_VN219_E2_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_E2_1", FlightManager );
    
    public static final Individual M_VN219_E2_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_E2_2", FlightManager );
    
    public static final Individual M_VN219_E2_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_E2_3", FlightManager );
    
    public static final Individual M_VN219_E3_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_E3_1", FlightManager );
    
    public static final Individual M_VN219_E3_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_E3_2", FlightManager );
    
    public static final Individual M_VN219_E3_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_E3_3", FlightManager );
    
    public static final Individual M_VN219_E4_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_E4_1", FlightManager );
    
    public static final Individual M_VN219_E4_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_E4_2", FlightManager );
    
    public static final Individual M_VN219_E4_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_E4_3", FlightManager );
    
    public static final Individual M_VN219_E5_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_E5_1", FlightManager );
    
    public static final Individual M_VN219_E5_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_E5_2", FlightManager );
    
    public static final Individual M_VN219_E5_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN219_E5_3", FlightManager );
    
    public static final Individual P135 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P135", Price );
    
    public static final Individual P195 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P195", Price );
    
    public static final Individual PQC = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#PQC", Airport );
    
    public static final Individual PXU = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#PXU", Airport );
    
    public static final Individual P_120 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_120", Price );
    
    public static final Individual P_125 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_125", Price );
    
    public static final Individual P_130 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_130", Price );
    
    public static final Individual P_140 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_140", Price );
    
    public static final Individual P_145 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_145", Price );
    
    public static final Individual P_150 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_150", Price );
    
    public static final Individual P_155 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_155", Price );
    
    public static final Individual P_160 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_160", Price );
    
    public static final Individual P_165 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_165", Price );
    
    public static final Individual P_170 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_170", Price );
    
    public static final Individual P_175 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_175", Price );
    
    public static final Individual P_180 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_180", Price );
    
    public static final Individual P_185 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_185", Price );
    
    public static final Individual P_190 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_190", Price );
    
    public static final Individual P_200 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_200", Price );
    
    public static final Individual P_205 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_205", Price );
    
    public static final Individual P_210 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_210", Price );
    
    public static final Individual P_95 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_95", Price );
    
    public static final Individual SGN = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#SGN", Airport );
    
    public static final Individual TBB = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#TBB", Airport );
    
    public static final Individual TaySon = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#TaySon", Adress );
    
    public static final Individual ThanhXuan = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#ThanhXuan", Adress );
    
    public static final Individual ThanhXuan_FlightAgent = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#ThanhXuan_FlightAgent", FlightAgent );
    
    public static final Individual UIH = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#UIH", Airport );
    
    public static final Individual VCL = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VCL", Airport );
    
    public static final Individual VII = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VII", Airport );
    
    public static final Individual VKG = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VKG", Airport );
    
    public static final Individual VN213_B1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN213_B1", Flight );
    
    public static final Individual VN213_B2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN213_B2", Flight );
    
    public static final Individual VN213_B3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN213_B3", Flight );
    
    public static final Individual VN213_B4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN213_B4", Flight );
    
    public static final Individual VN213_B5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN213_B5", Flight );
    
    public static final Individual VN213_E1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN213_E1", Flight );
    
    public static final Individual VN213_E2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN213_E2", Flight );
    
    public static final Individual VN213_E3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN213_E3", Flight );
    
    public static final Individual VN213_E4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN213_E4", Flight );
    
    public static final Individual VN213_E5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN213_E5", Flight );
    
    public static final Individual VN217_B1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN217_B1", Flight );
    
    public static final Individual VN217_B2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN217_B2", Flight );
    
    public static final Individual VN217_B3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN217_B3", Flight );
    
    public static final Individual VN217_B4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN217_B4", Flight );
    
    public static final Individual VN217_B5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN217_B5", Flight );
    
    public static final Individual VN217_E1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN217_E1", Flight );
    
    public static final Individual VN217_E2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN217_E2", Flight );
    
    public static final Individual VN217_E3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN217_E3", Flight );
    
    public static final Individual VN217_E4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN217_E4", Flight );
    
    public static final Individual VN217_E5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN217_E5", Flight );
    
    public static final Individual VN219_B1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN219_B1", Flight );
    
    public static final Individual VN219_B2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN219_B2", Flight );
    
    public static final Individual VN219_B3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN219_B3", Flight );
    
    public static final Individual VN219_B4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN219_B4", Flight );
    
    public static final Individual VN219_B5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN219_B5", Flight );
    
    public static final Individual VN219_E1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN219_E1", Flight );
    
    public static final Individual VN219_E2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN219_E2", Flight );
    
    public static final Individual VN219_E3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN219_E3", Flight );
    
    public static final Individual VN219_E4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN219_E4", Flight );
    
    public static final Individual VN219_E5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN219_E5", Flight );
    
    public static final Individual VN225_B1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN225_B1", Flight );
    
    public static final Individual VN225_B2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN225_B2", Flight );
    
    public static final Individual VN225_B3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN225_B3", Flight );
    
    public static final Individual VN225_B4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN225_B4", Flight );
    
    public static final Individual VN225_B5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN225_B5", Flight );
    
    public static final Individual VN225_E1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN225_E1", Flight );
    
    public static final Individual VN225_E2 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN225_E2", Flight );
    
    public static final Individual VN225_E3 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN225_E3", Flight );
    
    public static final Individual VN225_E4 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN225_E4", Flight );
    
    public static final Individual VN225_E5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN225_E5", Flight );
    
    public static final Individual Vi_vu = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#Vi_vu", FlightAgentInfo );
    
    public static final Individual achau = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#achau", FlightAgent );
    
}