/* CVS $Id: $ */
package com.ptit.travel.jane.flight; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:/C:/Program%20Files/Protege_3.4/schemagen-temp.owl 
 * @author Auto-generated by schemagen on 27 Dec 2009 22:28 
 */
public class Flight {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.owl-ontologies.com/Flight.owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty hasAdress = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasAdress" );
    
    public static final ObjectProperty hasAgentFlightInfo = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasAgentFlightInfo" );
    
    public static final ObjectProperty hasAirplane = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasAirplane" );
    
    public static final ObjectProperty hasArrivalAirport = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasArrivalAirport" );
    
    public static final ObjectProperty hasArrivalDateTime = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasArrivalDateTime" );
    
    public static final ObjectProperty hasCustomer = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasCustomer" );
    
    public static final ObjectProperty hasDepartureAirport = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasDepartureAirport" );
    
    public static final ObjectProperty hasDepartureDateTime = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasDepartureDateTime" );
    
    public static final ObjectProperty hasFlight = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasFlight" );
    
    public static final ObjectProperty hasFlightAgentInfo = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasFlightAgentInfo" );
    
    public static final ObjectProperty hasFlightManager = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasFlightManager" );
    
    public static final ObjectProperty hasPrice = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasPrice" );
    
    public static final ObjectProperty hasSecurityCode = m_model.createObjectProperty( "http://www.owl-ontologies.com/Flight.owl#hasSecurityCode" );
    
    /** <p>Hang hang khong</p> */
    public static final DatatypeProperty airline = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#airline" );
    
    /** <p>Hang san xuat may bay (Airbus, Boeing)</p> */
    public static final DatatypeProperty airplaneMaker = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#airplaneMaker" );
    
    public static final DatatypeProperty airplaneType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#airplaneType" );
    
    public static final DatatypeProperty airportName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#airportName" );
    
    public static final DatatypeProperty arrivalAirportCity = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#arrivalAirportCity" );
    
    public static final DatatypeProperty bookNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#bookNumber" );
    
    public static final DatatypeProperty city = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#city" );
    
    /** <p>Ma hop dong</p> */
    public static final DatatypeProperty contractCode = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#contractCode" );
    
    public static final DatatypeProperty country = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#country" );
    
    /** <p>Ngay cu the</p> */
    public static final DatatypeProperty date = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#date" );
    
    public static final DatatypeProperty departureAirportCity = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#departureAirportCity" );
    
    public static final DatatypeProperty description = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#description" );
    
    public static final DatatypeProperty email = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#email" );
    
    public static final DatatypeProperty fax = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#fax" );
    
    public static final DatatypeProperty flightAgentName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#flightAgentName" );
    
    /** <p>Loai ve may bay</p> */
    public static final DatatypeProperty flightClass = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#flightClass" );
    
    public static final DatatypeProperty flightInformation = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#flightInformation" );
    
    /** <p>Ma so chuyen bay</p> */
    public static final DatatypeProperty flightNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#flightNumber" );
    
    public static final DatatypeProperty fullName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#fullName" );
    
    public static final DatatypeProperty gender = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#gender" );
    
    public static final DatatypeProperty introduce = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#introduce" );
    
    /** <p>Thong bao kem theo</p> */
    public static final DatatypeProperty notification = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#notification" );
    
    public static final DatatypeProperty password = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#password" );
    
    public static final DatatypeProperty phoneNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#phoneNumber" );
    
    public static final DatatypeProperty price = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#price" );
    
    public static final DatatypeProperty priceUnit = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#priceUnit" );
    
    public static final DatatypeProperty specificAdress = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#specificAdress" );
    
    /** <p>Thoi gian cu the trong ngay</p> */
    public static final DatatypeProperty time = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#time" );
    
    public static final DatatypeProperty totalBookNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#totalBookNumber" );
    
    public static final DatatypeProperty totalNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#totalNumber" );
    
    public static final DatatypeProperty username = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Flight.owl#username" );
    
    public static final OntClass Adress = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Adress" );
    
    public static final OntClass Airplane = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Airplane" );
    
    public static final OntClass Airport = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Airport" );
    
    public static final OntClass Customer = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Customer" );
    
    /** <p></p> */
    public static final OntClass Flight = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Flight" );
    
    public static final OntClass FlightAgent = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#FlightAgent" );
    
    public static final OntClass FlightAgentInfo = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#FlightAgentInfo" );
    
    public static final OntClass FlightBookContract = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#FlightBookContract" );
    
    public static final OntClass FlightManager = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#FlightManager" );
    
    public static final OntClass Msg_FlightAvailRQ = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_FlightAvailRQ" );
    
    public static final OntClass Msg_FlightAvailRS = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_FlightAvailRS" );
    
    public static final OntClass Msg_FlightBookChangeConfirmRQ = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_FlightBookChangeConfirmRQ" );
    
    public static final OntClass Msg_FlightBookChangeRQ = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_FlightBookChangeRQ" );
    
    public static final OntClass Msg_FlightBookChangeRS = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_FlightBookChangeRS" );
    
    public static final OntClass Msg_FlightBookRQ = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_FlightBookRQ" );
    
    public static final OntClass Msg_FlightBookRS = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_FlightBookRS" );
    
    public static final OntClass Msg_FlightRegisterRQ = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_FlightRegisterRQ" );
    
    public static final OntClass Msg_PublishFlightRQ = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Msg_PublishFlightRQ" );
    
    public static final OntClass PointOfTime = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#PointOfTime" );
    
    public static final OntClass Price = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#Price" );
    
    public static final OntClass SecurityCode = m_model.createClass( "http://www.owl-ontologies.com/Flight.owl#SecurityCode" );
    
    public static final Individual Airbus321 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#Airbus321", Airplane );
    
    public static final Individual Airbus_A320 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#Airbus_A320", Airplane );
    
    public static final Individual Boeing737 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#Boeing737", Airplane );
    
    public static final Individual Boeing_777 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#Boeing_777", Airplane );
    
    public static final Individual CXR = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#CXR", Airport );
    
    public static final Individual ConDao = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#ConDao", Airport );
    
    public static final Individual DAD = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#DAD", Airport );
    
    public static final Individual DIN = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#DIN", Airport );
    
    public static final Individual DLI = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#DLI", Airport );
    
    public static final Individual D_HN_10 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_HN_10", PointOfTime );
    
    public static final Individual D_HN_13 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_HN_13", PointOfTime );
    
    public static final Individual D_HN_15_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_HN_15_1", PointOfTime );
    
    public static final Individual D_HN_17 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_HN_17", PointOfTime );
    
    public static final Individual D_HN_19_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#D_HN_19_1", PointOfTime );
    
    public static final Individual Fokker70 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#Fokker70", Airplane );
    
    public static final Individual HAN = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#HAN", Airport );
    
    public static final Individual HN15_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#HN15_1", PointOfTime );
    
    public static final Individual HN_10_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#HN_10_1", PointOfTime );
    
    public static final Individual HN_11_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#HN_11_1", PointOfTime );
    
    public static final Individual HN_13_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#HN_13_1", PointOfTime );
    
    public static final Individual HN_17_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#HN_17_1", PointOfTime );
    
    public static final Individual HN_19_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#HN_19_1", PointOfTime );
    
    public static final Individual HN_8_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#HN_8_1", PointOfTime );
    
    public static final Individual HPH = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#HPH", Airport );
    
    public static final Individual HUI = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#HUI", Airport );
    
    public static final Individual M_VN217_B = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_B", FlightManager );
    
    public static final Individual M_VN217_E = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#M_VN217_E", FlightManager );
    
    public static final Individual PQC = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#PQC", Airport );
    
    public static final Individual PXU = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#PXU", Airport );
    
    public static final Individual P_12 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_12", Price );
    
    public static final Individual P_14 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_14", Price );
    
    public static final Individual P_15 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_15", Price );
    
    public static final Individual P_17 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_17", Price );
    
    public static final Individual P_19 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_19", Price );
    
    public static final Individual P_20 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_20", Price );
    
    public static final Individual P_9_5 = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#P_9.5", Price );
    
    public static final Individual SGN = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#SGN", Airport );
    
    public static final Individual TBB = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#TBB", Airport );
    
    public static final Individual UIH = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#UIH", Airport );
    
    public static final Individual VCL = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VCL", Airport );
    
    public static final Individual VII = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VII", Airport );
    
    public static final Individual VKG = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VKG", Airport );
    
    public static final Individual VN217_B = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN217_B", Flight );
    
    public static final Individual VN217_E = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN217_E", Flight );
    
    public static final Individual VN219_B = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN219_B", Flight );
    
    public static final Individual VN219_E = m_model.createIndividual( "http://www.owl-ontologies.com/Flight.owl#VN219_E", Flight );
    
}
