/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ptit.edu.travel.struts.form.hotel;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-23-2009
 * 
 * XDoclet definition:
 * @struts.form name="bookRoomInfoForm"
 */
public class BookRoomInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** endDate property */
	private String endDate;

	/** beginDate property */
	private String beginDate;

	/** destination property */
	private String destination;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the endDate.
	 * @return String
	 */
	public String getEndDate() {
		return endDate;
	}

	/** 
	 * Set the endDate.
	 * @param endDate The endDate to set
	 */
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	/** 
	 * Returns the beginDate.
	 * @return String
	 */
	public String getBeginDate() {
		return beginDate;
	}

	/** 
	 * Set the beginDate.
	 * @param beginDate The beginDate to set
	 */
	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}

	/** 
	 * Returns the destination.
	 * @return String
	 */
	public String getDestination() {
		return destination;
	}

	/** 
	 * Set the destination.
	 * @param destination The destination to set
	 */
	public void setDestination(String destination) {
		this.destination = destination;
	}
}