/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ptit.travel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import com.ptit.travel.struts.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-23-2009
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="LoginForm" input="/WEB-INF/pages/login/loginPage.jsp" parameter="action" scope="request" validate="true"
 * @struts.action-forward name="failure" path="failure.page"
 * @struts.action-forward name="success" path="success.page"
 */
public class LoginAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm LoginForm = (LoginForm) form;// TODO Auto-generated method stub
		return mapping.findForward("success");
	}
}