/* CVS $Id: $ */
package com.ptit.travel.jane.member; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:/C:/Program%20Files/Protege_3.4/schemagen-temp.owl 
 * @author Auto-generated by schemagen on 10 Jan 2010 01:32 
 */
public class Member {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.owl-ontologies.com/partner-info.owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty hasAddress = m_model.createObjectProperty( "http://www.owl-ontologies.com/partner-info.owl#hasAddress" );
    
    public static final DatatypeProperty city = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/partner-info.owl#city" );
    
    public static final DatatypeProperty country = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/partner-info.owl#country" );
    
    public static final DatatypeProperty discription = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/partner-info.owl#discription" );
    
    public static final DatatypeProperty email = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/partner-info.owl#email" );
    
    public static final DatatypeProperty fax = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/partner-info.owl#fax" );
    
    /** <p>name displayed when member login</p> */
    public static final DatatypeProperty fullName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/partner-info.owl#fullName" );
    
    public static final DatatypeProperty id = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/partner-info.owl#id" );
    
    /** <p></p> */
    public static final DatatypeProperty password = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/partner-info.owl#password" );
    
    public static final DatatypeProperty phoneNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/partner-info.owl#phoneNumber" );
    
    /** <p>breif the provided services</p> */
    public static final DatatypeProperty services = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/partner-info.owl#services" );
    
    public static final DatatypeProperty street = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/partner-info.owl#street" );
    
    public static final DatatypeProperty type = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/partner-info.owl#type" );
    
    /** <p>website of company group (option)</p> */
    public static final DatatypeProperty website = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/partner-info.owl#website" );
    
    public static final DatatypeProperty zipCode = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/partner-info.owl#zipCode" );
    
    public static final OntClass Address = m_model.createClass( "http://www.owl-ontologies.com/partner-info.owl#Address" );
    
    public static final OntClass Member = m_model.createClass( "http://www.owl-ontologies.com/partner-info.owl#Member" );
    
    public static final Individual Member_1 = m_model.createIndividual( "http://www.owl-ontologies.com/partner-info.owl#Member_1", Member );
    
    public static final Individual Member_2 = m_model.createIndividual( "http://www.owl-ontologies.com/partner-info.owl#Member_2", Member );
    
}
