/* CVS $Id: $ */
package Hotel; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:/C:/Program%20Files/Protege_3.4/schemagen-temp.owl 
 * @author Auto-generated by schemagen on 18 Nov 2009 22:24 
 */
public class Hotel {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.owl-ontologies.com/Travel.owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty HasName = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#HasName" );
    
    public static final ObjectProperty hasAccommodation = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasAccommodation" );
    
    public static final ObjectProperty hasAccommodationCategory = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasAccommodationCategory" );
    
    public static final ObjectProperty hasAccommodationInstitution = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasAccommodationInstitution" );
    
    public static final ObjectProperty hasAccommodationUnits = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasAccommodationUnits" );
    
    public static final ObjectProperty hasActivities = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasActivities" );
    
    public static final ObjectProperty hasActivity = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasActivity" );
    
    public static final ObjectProperty hasActivityType = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasActivityType" );
    
    public static final ObjectProperty hasAddress = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasAddress" );
    
    public static final ObjectProperty hasAdress = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasAdress" );
    
    public static final ObjectProperty hasAvailabilityPeriod = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasAvailabilityPeriod" );
    
    public static final ObjectProperty hasAverageTemperature = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasAverageTemperature" );
    
    public static final ObjectProperty hasBankDebit = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasBankDebit" );
    
    public static final ObjectProperty hasBedType = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasBedType" );
    
    public static final ObjectProperty hasBegin = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasBegin" );
    
    public static final ObjectProperty hasBeginPoint = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasBeginPoint" );
    
    public static final ObjectProperty hasBeginTime = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasBeginTime" );
    
    public static final ObjectProperty hasBookingFee = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasBookingFee" );
    
    public static final ObjectProperty hasCard = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasCard" );
    
    public static final ObjectProperty hasCategory = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasCategory" );
    
    public static final ObjectProperty hasCatering = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasCatering" );
    
    public static final ObjectProperty hasCateringType = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasCateringType" );
    
    public static final ObjectProperty hasCharacteristics = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasCharacteristics" );
    
    public static final ObjectProperty hasCharge = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasCharge" );
    
    public static final ObjectProperty hasClimate = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasClimate" );
    
    public static final ObjectProperty hasCloseSession = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasCloseSession" );
    
    public static final ObjectProperty hasContact = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasContact" );
    
    public static final ObjectProperty hasCouchetteBedPosition = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasCouchetteBedPosition" );
    
    public static final ObjectProperty hasCountry = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasCountry" );
    
    public static final ObjectProperty hasCountryName = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasCountryName" );
    
    public static final ObjectProperty hasCreditCard = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasCreditCard" );
    
    public static final ObjectProperty hasCuisine = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasCuisine" );
    
    public static final ObjectProperty hasCustomerData = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasCustomerData" );
    
    public static final ObjectProperty hasDestination = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasDestination" );
    
    public static final ObjectProperty hasEnd = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasEnd" );
    
    public static final ObjectProperty hasEndPoint = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasEndPoint" );
    
    public static final ObjectProperty hasEndTime = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasEndTime" );
    
    public static final ObjectProperty hasExclusiveDay = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasExclusiveDay" );
    
    public static final ObjectProperty hasExclusivePeriod = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasExclusivePeriod" );
    
    public static final ObjectProperty hasExtraBed = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasExtraBed" );
    
    public static final ObjectProperty hasFacilitites = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasFacilitites" );
    
    public static final ObjectProperty hasGuestRoom = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasGuestRoom" );
    
    public static final ObjectProperty hasGuidedTour = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasGuidedTour" );
    
    /** <p>Noi tra xe</p> */
    public static final ObjectProperty hasHandInStation = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasHandInStation" );
    
    public static final ObjectProperty hasHotel = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasHotel" );
    
    public static final ObjectProperty hasHotelActivities = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasHotelActivities" );
    
    public static final ObjectProperty hasHotelCartering = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasHotelCartering" );
    
    public static final ObjectProperty hasHotelCategory = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasHotelCategory" );
    
    public static final ObjectProperty hasHotelEquipment = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasHotelEquipment" );
    
    public static final ObjectProperty hasHotelFacilities = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasHotelFacilities" );
    
    public static final ObjectProperty hasHotelInfo = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasHotelInfo" );
    
    public static final ObjectProperty hasHotelLocation = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasHotelLocation" );
    
    public static final ObjectProperty hasHotelReservation = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasHotelReservation" );
    
    public static final ObjectProperty hasHotelRoom = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasHotelRoom" );
    
    public static final ObjectProperty hasHotelSize = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasHotelSize" );
    
    public static final ObjectProperty hasHotelType = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasHotelType" );
    
    public static final ObjectProperty hasHours = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasHours" );
    
    public static final ObjectProperty hasInclusiveDay = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasInclusiveDay" );
    
    public static final ObjectProperty hasInclusivePeriod = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasInclusivePeriod" );
    
    public static final ObjectProperty hasInstitution = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasInstitution" );
    
    public static final ObjectProperty hasLanguage = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasLanguage" );
    
    public static final ObjectProperty hasLivingRoomEquipment = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasLivingRoomEquipment" );
    
    public static final ObjectProperty hasLuggageType = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasLuggageType" );
    
    public static final ObjectProperty hasMealType = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasMealType" );
    
    public static final ObjectProperty hasMeetingRoom = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasMeetingRoom" );
    
    public static final ObjectProperty hasMeetingRoomEquipment = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasMeetingRoomEquipment" );
    
    public static final ObjectProperty hasMonth = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasMonth" );
    
    public static final ObjectProperty hasMonthTemperature = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasMonthTemperature" );
    
    public static final ObjectProperty hasMsg_HotelSearchRS = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasMsg_HotelSearchRS" );
    
    public static final ObjectProperty hasNumberOfUnits = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasNumberOfUnits" );
    
    public static final ObjectProperty hasOfferedProduct = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasOfferedProduct" );
    
    public static final ObjectProperty hasOpenSession = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasOpenSession" );
    
    public static final ObjectProperty hasOpeningHours = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasOpeningHours" );
    
    public static final ObjectProperty hasOrganizer = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasOrganizer" );
    
    public static final ObjectProperty hasParkingPlace = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasParkingPlace" );
    
    public static final ObjectProperty hasPaymentMethod = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasPaymentMethod" );
    
    public static final ObjectProperty hasPaymentMethodType = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasPaymentMethodType" );
    
    public static final ObjectProperty hasPeriodOfDay = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasPeriodOfDay" );
    
    public static final ObjectProperty hasPeriodOfTime = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasPeriodOfTime" );
    
    public static final ObjectProperty hasPersonType = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasPersonType" );
    
    /** <p>Noi nhan xe</p> */
    public static final ObjectProperty hasPickUpStation = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasPickUpStation" );
    
    public static final ObjectProperty hasPieceOfLuggage = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasPieceOfLuggage" );
    
    public static final ObjectProperty hasPrice = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasPrice" );
    
    public static final ObjectProperty hasProductType = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasProductType" );
    
    public static final ObjectProperty hasRequestorID = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasRequestorID" );
    
    public static final ObjectProperty hasRestaurant = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasRestaurant" );
    
    public static final ObjectProperty hasRoom = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasRoom" );
    
    public static final ObjectProperty hasRoomLocation = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasRoomLocation" );
    
    public static final ObjectProperty hasRoomType = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasRoomType" );
    
    public static final ObjectProperty hasSection = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasSection" );
    
    public static final ObjectProperty hasServiceState = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasServiceState" );
    
    public static final ObjectProperty hasSleeperCompartmentType = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasSleeperCompartmentType" );
    
    public static final ObjectProperty hasSmoker = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasSmoker" );
    
    public static final ObjectProperty hasSpeaker = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasSpeaker" );
    
    public static final ObjectProperty hasState = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasState" );
    
    public static final ObjectProperty hasTargetGroup = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasTargetGroup" );
    
    public static final ObjectProperty hasTaxAmount = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#hasTaxAmount" );
    
    public static final ObjectProperty inverse_of_isParkingPlaceOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#inverse_of_isParkingPlaceOf" );
    
    public static final ObjectProperty isAccommodationCategoryOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isAccommodationCategoryOf" );
    
    public static final ObjectProperty isAccommodationInstitutionOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isAccommodationInstitutionOf" );
    
    public static final ObjectProperty isAccommodationOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isAccommodationOf" );
    
    public static final ObjectProperty isAccomodationUnitsOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isAccomodationUnitsOf" );
    
    public static final ObjectProperty isAcitivityTypeOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isAcitivityTypeOf" );
    
    public static final ObjectProperty isActivityOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isActivityOf" );
    
    public static final ObjectProperty isAdressOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isAdressOf" );
    
    public static final ObjectProperty isAvailabilityPeriodOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isAvailabilityPeriodOf" );
    
    public static final ObjectProperty isAverageTemperatureOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isAverageTemperatureOf" );
    
    public static final ObjectProperty isBankDebitOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isBankDebitOf" );
    
    public static final ObjectProperty isBedTypeOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isBedTypeOf" );
    
    public static final ObjectProperty isBeginOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isBeginOf" );
    
    public static final ObjectProperty isBeginPointOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isBeginPointOf" );
    
    public static final ObjectProperty isBeginTimeOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isBeginTimeOf" );
    
    public static final ObjectProperty isCateringOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isCateringOf" );
    
    public static final ObjectProperty isCateringTypeOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isCateringTypeOf" );
    
    public static final ObjectProperty isCloseSessionOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isCloseSessionOf" );
    
    public static final ObjectProperty isContactOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isContactOf" );
    
    public static final ObjectProperty isCouchetteBedPositionOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isCouchetteBedPositionOf" );
    
    public static final ObjectProperty isCountryNameOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isCountryNameOf" );
    
    public static final ObjectProperty isCountryOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isCountryOf" );
    
    public static final ObjectProperty isCreditCard = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isCreditCard" );
    
    public static final ObjectProperty isCuisineTypeOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isCuisineTypeOf" );
    
    public static final ObjectProperty isCustomerOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isCustomerOf" );
    
    public static final ObjectProperty isDestination = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isDestination" );
    
    public static final ObjectProperty isEndOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isEndOf" );
    
    public static final ObjectProperty isEndPointOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isEndPointOf" );
    
    public static final ObjectProperty isEndTimeOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isEndTimeOf" );
    
    public static final ObjectProperty isExclusiveDayOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isExclusiveDayOf" );
    
    public static final ObjectProperty isExclusivePeriodOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isExclusivePeriodOf" );
    
    public static final ObjectProperty isExtraBedOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isExtraBedOf" );
    
    public static final ObjectProperty isGuidedTourOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isGuidedTourOf" );
    
    public static final ObjectProperty isHandInStationOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isHandInStationOf" );
    
    public static final ObjectProperty isHotelActivitiesof = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isHotelActivitiesof" );
    
    public static final ObjectProperty isHotelCarteringOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isHotelCarteringOf" );
    
    public static final ObjectProperty isHotelCategoryOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isHotelCategoryOf" );
    
    public static final ObjectProperty isHotelEquimentOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isHotelEquimentOf" );
    
    public static final ObjectProperty isHotelFacilitiesOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isHotelFacilitiesOf" );
    
    public static final ObjectProperty isHotelInfoOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isHotelInfoOf" );
    
    public static final ObjectProperty isHotelLocationOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isHotelLocationOf" );
    
    public static final ObjectProperty isHotelOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isHotelOf" );
    
    public static final ObjectProperty isHotelRoomOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isHotelRoomOf" );
    
    public static final ObjectProperty isHotelSizeOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isHotelSizeOf" );
    
    public static final ObjectProperty isHotelTypeOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isHotelTypeOf" );
    
    /** <p>Gio giao dich tai khach san.</p> */
    public static final ObjectProperty isHoursOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isHoursOf" );
    
    public static final ObjectProperty isInclusiveDayof = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isInclusiveDayof" );
    
    public static final ObjectProperty isInclusivePeriodOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isInclusivePeriodOf" );
    
    public static final ObjectProperty isInstitutionOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isInstitutionOf" );
    
    public static final ObjectProperty isLanguageOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isLanguageOf" );
    
    public static final ObjectProperty isLuggageTypeOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isLuggageTypeOf" );
    
    public static final ObjectProperty isMealTypeOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isMealTypeOf" );
    
    public static final ObjectProperty isMeetingRoomEquipmentOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isMeetingRoomEquipmentOf" );
    
    public static final ObjectProperty isMonthOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isMonthOf" );
    
    public static final ObjectProperty isMonthTemperatureOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isMonthTemperatureOf" );
    
    public static final ObjectProperty isNumberOfUnitsOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isNumberOfUnitsOf" );
    
    public static final ObjectProperty isOfferedProductOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isOfferedProductOf" );
    
    public static final ObjectProperty isOpenSessionOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isOpenSessionOf" );
    
    public static final ObjectProperty isOpeningHoursOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isOpeningHoursOf" );
    
    public static final ObjectProperty isOrganizerOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isOrganizerOf" );
    
    public static final ObjectProperty isParkingPlaceOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isParkingPlaceOf" );
    
    public static final ObjectProperty isPaymentMethodTypeOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isPaymentMethodTypeOf" );
    
    public static final ObjectProperty isPeriodOfDayOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isPeriodOfDayOf" );
    
    public static final ObjectProperty isPeriodOfTimeOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isPeriodOfTimeOf" );
    
    public static final ObjectProperty isPersonTypeOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isPersonTypeOf" );
    
    public static final ObjectProperty isPickUpStationOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isPickUpStationOf" );
    
    public static final ObjectProperty isPieceOfLuggageOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isPieceOfLuggageOf" );
    
    public static final ObjectProperty isPriceOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isPriceOf" );
    
    public static final ObjectProperty isProductTypeOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isProductTypeOf" );
    
    public static final ObjectProperty isRoomEquipmentOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isRoomEquipmentOf" );
    
    public static final ObjectProperty isRoomLocationOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isRoomLocationOf" );
    
    public static final ObjectProperty isRoomTypeOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isRoomTypeOf" );
    
    public static final ObjectProperty isServiceStateOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isServiceStateOf" );
    
    public static final ObjectProperty isSleeperCompartmentTypeOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isSleeperCompartmentTypeOf" );
    
    public static final ObjectProperty isSmokerOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isSmokerOf" );
    
    public static final ObjectProperty isStateOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isStateOf" );
    
    public static final ObjectProperty isTargetGroupOf = m_model.createObjectProperty( "http://www.owl-ontologies.com/Travel.owl#isTargetGroupOf" );
    
    /** <p>Bao gom viec dat truoc</p> */
    public static final DatatypeProperty AdvancedBookingInd = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#AdvancedBookingInd" );
    
    public static final DatatypeProperty AlterType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#AlterType" );
    
    /** <p>Luong tien te (CarRental)</p> */
    public static final DatatypeProperty Amount = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Amount" );
    
    public static final DatatypeProperty AmountBeforeTax = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#AmountBeforeTax" );
    
    public static final DatatypeProperty AreaWeather = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#AreaWeather" );
    
    /** <p>Chi phuc vu doi tuong la khach hang vua thuc hien chuyen bay</p> */
    public static final DatatypeProperty ArriveByFlight = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#ArriveByFlight" );
    
    public static final DatatypeProperty Bookingchannel = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Bookingchannel" );
    
    /** <p>Tinh phi khi huy hop dong</p> */
    public static final DatatypeProperty CancellationPenaltyInd = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#CancellationPenaltyInd" );
    
    public static final DatatypeProperty CardNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#CardNumber" );
    
    public static final DatatypeProperty CardType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#CardType" );
    
    public static final DatatypeProperty Changes = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Changes" );
    
    public static final DatatypeProperty CheckIn = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#CheckIn" );
    
    public static final DatatypeProperty CheckOut = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#CheckOut" );
    
    public static final DatatypeProperty ClosingTime = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#ClosingTime" );
    
    public static final DatatypeProperty Comment = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Comment" );
    
    public static final DatatypeProperty CompanyName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#CompanyName" );
    
    public static final DatatypeProperty ContactInfo = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#ContactInfo" );
    
    public static final DatatypeProperty CurrencyCode = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#CurrencyCode" );
    
    public static final DatatypeProperty Day = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Day" );
    
    public static final DatatypeProperty Description = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Description" );
    
    public static final DatatypeProperty DescriptionService = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#DescriptionService" );
    
    public static final DatatypeProperty Domain = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Domain" );
    
    public static final DatatypeProperty Duration = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Duration" );
    
    public static final DatatypeProperty EffectiveDate = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#EffectiveDate" );
    
    public static final DatatypeProperty Email = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Email" );
    
    public static final DatatypeProperty FromDate = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#FromDate" );
    
    public static final DatatypeProperty GivenName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#GivenName" );
    
    /** <p>Yeu cau phai dam bao</p> */
    public static final DatatypeProperty GuaranteeReqInd = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#GuaranteeReqInd" );
    
    public static final DatatypeProperty GuestCount = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#GuestCount" );
    
    public static final DatatypeProperty HotelName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#HotelName" );
    
    public static final DatatypeProperty IDService = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#IDService" );
    
    public static final DatatypeProperty LargestRoomSpace = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#LargestRoomSpace" );
    
    public static final DatatypeProperty LuggageTypeConsistOf = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#LuggageTypeConsistOf" );
    
    /** <p>Thuoc tinh nay dung de xac dinh thoi gian o toi da la bao lau</p> */
    public static final DatatypeProperty MaxOccupancy = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#MaxOccupancy" );
    
    public static final DatatypeProperty MaxSeatingCapacity = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#MaxSeatingCapacity" );
    
    public static final DatatypeProperty MaxSingleParty = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#MaxSingleParty" );
    
    public static final DatatypeProperty MeetingRoomCount = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#MeetingRoomCount" );
    
    /** <p>Mat phi khi thay doi hop dong</p> */
    public static final DatatypeProperty ModificationPenaltyInd = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#ModificationPenaltyInd" );
    
    public static final DatatypeProperty NamePrefix = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#NamePrefix" );
    
    public static final DatatypeProperty Night = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Night" );
    
    public static final DatatypeProperty NotifyMessage = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#NotifyMessage" );
    
    public static final DatatypeProperty OfferBreakfast = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#OfferBreakfast" );
    
    public static final DatatypeProperty OfferBrunch = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#OfferBrunch" );
    
    public static final DatatypeProperty OfferDinner = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#OfferDinner" );
    
    public static final DatatypeProperty OfferLunch = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#OfferLunch" );
    
    /** <p>Thue xe tai dau thi phai tra xe tai day</p> */
    public static final DatatypeProperty OneWayPolicy = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#OneWayPolicy" );
    
    public static final DatatypeProperty OpeningTime = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#OpeningTime" );
    
    public static final DatatypeProperty Percentage = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Percentage" );
    
    public static final DatatypeProperty Phone = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Phone" );
    
    public static final DatatypeProperty PhoneNumer = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#PhoneNumer" );
    
    public static final DatatypeProperty Quanlity = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Quanlity" );
    
    public static final DatatypeProperty RateDescription = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#RateDescription" );
    
    public static final DatatypeProperty RestaurantName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#RestaurantName" );
    
    public static final DatatypeProperty Result = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Result" );
    
    public static final DatatypeProperty SecondLargestSeatingCapacity = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#SecondLargestSeatingCapacity" );
    
    public static final DatatypeProperty SendGuestRoom = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#SendGuestRoom" );
    
    public static final DatatypeProperty SendHotelInfo = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#SendHotelInfo" );
    
    public static final DatatypeProperty SendMeetingRooms = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#SendMeetingRooms" );
    
    public static final DatatypeProperty SendPolicies = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#SendPolicies" );
    
    public static final DatatypeProperty SendRestaurants = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#SendRestaurants" );
    
    public static final DatatypeProperty ServiceName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#ServiceName" );
    
    public static final DatatypeProperty ServiceType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#ServiceType" );
    
    public static final DatatypeProperty SmallestSeatingCapacity = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#SmallestSeatingCapacity" );
    
    public static final DatatypeProperty StarNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#StarNumber" );
    
    public static final DatatypeProperty Sumame = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Sumame" );
    
    /** <p>Co bao gom thue hay khong</p> */
    public static final DatatypeProperty TaxInclusive = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#TaxInclusive" );
    
    public static final DatatypeProperty ToDate = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#ToDate" );
    
    /** <p>Tong luong tien</p> */
    public static final DatatypeProperty Total = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Total" );
    
    public static final DatatypeProperty Type = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Type" );
    
    /** <p>Luong tien tren moi don vi (Vi du: 100 USD/ngay)</p> */
    public static final DatatypeProperty UnitCharge = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#UnitCharge" );
    
    public static final DatatypeProperty Unlimited = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#Unlimited" );
    
    public static final DatatypeProperty WhenBuilt = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#WhenBuilt" );
    
    public static final DatatypeProperty accommodationCategory = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#accommodationCategory" );
    
    public static final DatatypeProperty accountNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#accountNumber" );
    
    public static final DatatypeProperty accountOwner = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#accountOwner" );
    
    public static final DatatypeProperty age = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#age" );
    
    public static final DatatypeProperty airConditioningIncl = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#airConditioningIncl" );
    
    public static final DatatypeProperty aparmentEquipment = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#aparmentEquipment" );
    
    public static final DatatypeProperty apartmentCategory = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#apartmentCategory" );
    
    public static final DatatypeProperty apartmentInstitutionType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#apartmentInstitutionType" );
    
    public static final DatatypeProperty apartmentSize = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#apartmentSize" );
    
    public static final DatatypeProperty asemble = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#asemble" );
    
    public static final DatatypeProperty attractionName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#attractionName" );
    
    public static final DatatypeProperty availability = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#availability" );
    
    public static final DatatypeProperty availabilityNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#availabilityNumber" );
    
    public static final DatatypeProperty bankCode = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#bankCode" );
    
    public static final DatatypeProperty baseRateTotal = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#baseRateTotal" );
    
    public static final DatatypeProperty bedType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#bedType" );
    
    public static final DatatypeProperty beginTime = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#beginTime" );
    
    public static final DatatypeProperty cardNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#cardNumber" );
    
    public static final DatatypeProperty cateringPrice = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#cateringPrice" );
    
    public static final DatatypeProperty cateringType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#cateringType" );
    
    public static final DatatypeProperty checkInTime = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#checkInTime" );
    
    public static final DatatypeProperty checkOutTime = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#checkOutTime" );
    
    public static final DatatypeProperty city = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#city" );
    
    public static final DatatypeProperty cityAttribute = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#cityAttribute" );
    
    public static final DatatypeProperty cityName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#cityName" );
    
    public static final DatatypeProperty climateCategory = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#climateCategory" );
    
    public static final DatatypeProperty couchetteBedPosition = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#couchetteBedPosition" );
    
    public static final DatatypeProperty country = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#country" );
    
    public static final DatatypeProperty courseSubject = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#courseSubject" );
    
    public static final DatatypeProperty cuisineType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#cuisineType" );
    
    public static final DatatypeProperty datatypeProperty_16 = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#datatypeProperty_16" );
    
    public static final DatatypeProperty date = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#date" );
    
    public static final DatatypeProperty dayOfWeek = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#dayOfWeek" );
    
    public static final DatatypeProperty destination = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#destination" );
    
    public static final DatatypeProperty difficultDegree = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#difficultDegree" );
    
    public static final DatatypeProperty director = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#director" );
    
    public static final DatatypeProperty domain = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#domain" );
    
    public static final DatatypeProperty duration = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#duration" );
    
    public static final DatatypeProperty endTime = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#endTime" );
    
    public static final DatatypeProperty epochConsistOf = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#epochConsistOf" );
    
    public static final DatatypeProperty expirationDate = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#expirationDate" );
    
    public static final DatatypeProperty facilityPrice = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#facilityPrice" );
    
    public static final DatatypeProperty furnishingsStyle = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#furnishingsStyle" );
    
    public static final DatatypeProperty gastronomyCategory = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#gastronomyCategory" );
    
    public static final DatatypeProperty gastronomyEquipment = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#gastronomyEquipment" );
    
    public static final DatatypeProperty gastronomySize = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#gastronomySize" );
    
    public static final DatatypeProperty hasPayment = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#hasPayment" );
    
    public static final DatatypeProperty hotelActivities = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#hotelActivities" );
    
    public static final DatatypeProperty hotelCategory = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#hotelCategory" );
    
    public static final DatatypeProperty hotelEquipment = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#hotelEquipment" );
    
    public static final DatatypeProperty hotelFacilities = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#hotelFacilities" );
    
    public static final DatatypeProperty hotelSize = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#hotelSize" );
    
    public static final DatatypeProperty hotelType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#hotelType" );
    
    public static final DatatypeProperty identifier = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#identifier" );
    
    public static final DatatypeProperty info = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#info" );
    
    public static final DatatypeProperty institutionName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#institutionName" );
    
    public static final DatatypeProperty language = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#language" );
    
    public static final DatatypeProperty largestSeatingCapacity = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#largestSeatingCapacity" );
    
    public static final DatatypeProperty length = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#length" );
    
    public static final DatatypeProperty linkType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#linkType" );
    
    public static final DatatypeProperty location = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#location" );
    
    public static final DatatypeProperty locationConsistOf = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#locationConsistOf" );
    
    public static final DatatypeProperty mealType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#mealType" );
    
    public static final DatatypeProperty meetingRoomEquipment = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#meetingRoomEquipment" );
    
    public static final DatatypeProperty month = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#month" );
    
    public static final DatatypeProperty name = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#name" );
    
    public static final DatatypeProperty number = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#number" );
    
    public static final DatatypeProperty numberOfDay = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#numberOfDay" );
    
    public static final DatatypeProperty numberOfFloor = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#numberOfFloor" );
    
    public static final DatatypeProperty numberOfLivingRoom = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#numberOfLivingRoom" );
    
    public static final DatatypeProperty numberOfMeetingRoom = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#numberOfMeetingRoom" );
    
    /** <p>So luong day trong khach san</p> */
    public static final DatatypeProperty numberOfPartyRoom = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#numberOfPartyRoom" );
    
    public static final DatatypeProperty numberOfPerson = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#numberOfPerson" );
    
    public static final DatatypeProperty numberOfPersons = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#numberOfPersons" );
    
    public static final DatatypeProperty numberOfSeat = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#numberOfSeat" );
    
    public static final DatatypeProperty numberPersons = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#numberPersons" );
    
    /** <p>Ma so cua doi tuong co the thue</p> */
    public static final DatatypeProperty numberRenableObjectUnit = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#numberRenableObjectUnit" );
    
    public static final DatatypeProperty numberRoom = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#numberRoom" );
    
    public static final DatatypeProperty numberUnit = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#numberUnit" );
    
    public static final DatatypeProperty numbers = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#numbers" );
    
    public static final DatatypeProperty numbetOfNight = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#numbetOfNight" );
    
    public static final DatatypeProperty organization = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#organization" );
    
    public static final DatatypeProperty organizerName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#organizerName" );
    
    public static final DatatypeProperty orgerni = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#orgerni" );
    
    public static final DatatypeProperty owner = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#owner" );
    
    public static final DatatypeProperty participantIdentifier = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#participantIdentifier" );
    
    public static final DatatypeProperty password = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#password" );
    
    public static final DatatypeProperty paymentType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#paymentType" );
    
    /** <p></p> */
    public static final DatatypeProperty personNum = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#personNum" );
    
    public static final DatatypeProperty personNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#personNumber" );
    
    public static final DatatypeProperty personType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#personType" );
    
    public static final DatatypeProperty pitchConnectioncon = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#pitchConnectioncon" );
    
    public static final DatatypeProperty pitchLocation = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#pitchLocation" );
    
    public static final DatatypeProperty price = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#price" );
    
    public static final DatatypeProperty prices = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#prices" );
    
    public static final DatatypeProperty processState = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#processState" );
    
    public static final DatatypeProperty productType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#productType" );
    
    public static final DatatypeProperty protagonist = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#protagonist" );
    
    public static final DatatypeProperty rating = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#rating" );
    
    public static final DatatypeProperty regionName = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#regionName" );
    
    /** <p>Ten cong ty cho thue xe</p> */
    public static final DatatypeProperty renter = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#renter" );
    
    public static final DatatypeProperty roomEquipment = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#roomEquipment" );
    
    public static final DatatypeProperty roomLocation = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#roomLocation" );
    
    public static final DatatypeProperty roomNumber = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#roomNumber" );
    
    public static final DatatypeProperty roomType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#roomType" );
    
    public static final DatatypeProperty serviceState = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#serviceState" );
    
    public static final DatatypeProperty sessionIdentifier = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#sessionIdentifier" );
    
    public static final DatatypeProperty size = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#size" );
    
    public static final DatatypeProperty sleeperCompartmentType = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#sleeperCompartmentType" );
    
    public static final DatatypeProperty smallestRoomSpace = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#smallestRoomSpace" );
    
    public static final DatatypeProperty smoker = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#smoker" );
    
    public static final DatatypeProperty sportRoom = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#sportRoom" );
    
    public static final DatatypeProperty street = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#street" );
    
    public static final DatatypeProperty tableLocation = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#tableLocation" );
    
    public static final DatatypeProperty targetGroup = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#targetGroup" );
    
    public static final DatatypeProperty tax = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#tax" );
    
    public static final DatatypeProperty temperature = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#temperature" );
    
    public static final DatatypeProperty time = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#time" );
    
    public static final DatatypeProperty type = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#type" );
    
    public static final DatatypeProperty zipCode = m_model.createDatatypeProperty( "http://www.owl-ontologies.com/Travel.owl#zipCode" );
    
    public static final OntClass Address = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Address" );
    
    public static final OntClass AvailabilityPeriod = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#AvailabilityPeriod" );
    
    public static final OntClass BankDebit = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#BankDebit" );
    
    public static final OntClass BedType = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#BedType" );
    
    /** <p>kieu dich vu an uong (bua sang, bua trua, an nhe ...)</p> */
    public static final OntClass CateringType = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#CateringType" );
    
    /** <p></p> */
    public static final OntClass Charge = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Charge" );
    
    public static final OntClass Climate = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Climate" );
    
    public static final OntClass CloseSession = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#CloseSession" );
    
    public static final OntClass Contact = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Contact" );
    
    public static final OntClass CountryName = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#CountryName" );
    
    public static final OntClass CreditCard = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#CreditCard" );
    
    /** <p>kieu nau an (theo phong cac tung quoc gia)</p> */
    public static final OntClass CuisineType = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#CuisineType" );
    
    public static final OntClass Customer = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Customer" );
    
    public static final OntClass DayOfWeek = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#DayOfWeek" );
    
    public static final OntClass Destination = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Destination" );
    
    public static final OntClass Distance = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Distance" );
    
    public static final OntClass ExtraBed = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#ExtraBed" );
    
    public static final OntClass Facilities = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Facilities" );
    
    public static final OntClass FacilityInfo = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#FacilityInfo" );
    
    public static final OntClass GuestRoom = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#GuestRoom" );
    
    public static final OntClass Hotel = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Hotel" );
    
    public static final OntClass HotelActivities = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#HotelActivities" );
    
    public static final OntClass HotelCatering = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#HotelCatering" );
    
    public static final OntClass HotelEquipment = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#HotelEquipment" );
    
    public static final OntClass HotelFacilities = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#HotelFacilities" );
    
    public static final OntClass HotelInfo = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#HotelInfo" );
    
    public static final OntClass HotelLocation = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#HotelLocation" );
    
    public static final OntClass HotelReservation = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#HotelReservation" );
    
    public static final OntClass HotelRoom = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#HotelRoom" );
    
    public static final OntClass HotelSize = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#HotelSize" );
    
    public static final OntClass HotelType = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#HotelType" );
    
    public static final OntClass Hours = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Hours" );
    
    public static final OntClass Language = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Language" );
    
    public static final OntClass LivingRoom = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#LivingRoom" );
    
    public static final OntClass LivingRoomEquipment = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#LivingRoomEquipment" );
    
    public static final OntClass LuggageType = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#LuggageType" );
    
    /** <p>che do cua bua an (danh cho ng an kieng hay k...)</p> */
    public static final OntClass MealType = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#MealType" );
    
    public static final OntClass MeetingRoom = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#MeetingRoom" );
    
    public static final OntClass MeetingRoomEquipment = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#MeetingRoomEquipment" );
    
    public static final OntClass MessageHotel = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#MessageHotel" );
    
    public static final OntClass Month = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Month" );
    
    public static final OntClass MonthTemperature = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#MonthTemperature" );
    
    public static final OntClass Msg_HotelAlterBookedServiceRQ = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Msg_HotelAlterBookedServiceRQ" );
    
    public static final OntClass Msg_HotelAlterServiceRQ = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Msg_HotelAlterServiceRQ" );
    
    public static final OntClass Msg_HotelAvailabilityRQ = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Msg_HotelAvailabilityRQ" );
    
    public static final OntClass Msg_HotelAvailabilityRS = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Msg_HotelAvailabilityRS" );
    
    public static final OntClass Msg_HotelBookRQ = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Msg_HotelBookRQ" );
    
    public static final OntClass Msg_HotelBookRS = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Msg_HotelBookRS" );
    
    public static final OntClass Msg_HotelViewBookedServiceInfomation = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Msg_HotelViewBookedServiceInfomation" );
    
    public static final OntClass Msg_HotelViewDetailServiceRQ = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Msg_HotelViewDetailServiceRQ" );
    
    public static final OntClass Msg_PublishHotelServiceRQ = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Msg_PublishHotelServiceRQ" );
    
    public static final OntClass Msg_PublishHotelServiceRS = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Msg_PublishHotelServiceRS" );
    
    public static final OntClass Name = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Name" );
    
    public static final OntClass OpenSession = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#OpenSession" );
    
    public static final OntClass ParkingPlace = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#ParkingPlace" );
    
    public static final OntClass PartyRoom = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#PartyRoom" );
    
    public static final OntClass PaymentMethod = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#PaymentMethod" );
    
    public static final OntClass PaymentMethodType = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#PaymentMethodType" );
    
    public static final OntClass Period = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Period" );
    
    public static final OntClass PeriodOfDay = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#PeriodOfDay" );
    
    public static final OntClass PersonType = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#PersonType" );
    
    public static final OntClass PieceOfLuggage = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#PieceOfLuggage" );
    
    public static final OntClass PointOfTime = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#PointOfTime" );
    
    public static final OntClass Price = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Price" );
    
    public static final OntClass Restaurant = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#Restaurant" );
    
    public static final OntClass RoomLocation = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#RoomLocation" );
    
    public static final OntClass RoomType = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#RoomType" );
    
    public static final OntClass SportRoom = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#SportRoom" );
    
    public static final OntClass TargetGroup = m_model.createClass( "http://www.owl-ontologies.com/Travel.owl#TargetGroup" );
    
    public static final Individual BedType_57 = m_model.createIndividual( "http://www.owl-ontologies.com/Travel.owl#BedType_57", BedType );
    
    public static final Individual D1 = m_model.createIndividual( "http://www.owl-ontologies.com/Travel.owl#D1", Destination );
    
    public static final Individual D2 = m_model.createIndividual( "http://www.owl-ontologies.com/Travel.owl#D2", Destination );
    
    public static final Individual Destinationa_22 = m_model.createIndividual( "http://www.owl-ontologies.com/Travel.owl#Destinationa_22", Destination );
    
    public static final Individual FacilityInfo_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Travel.owl#FacilityInfo_2", FacilityInfo );
    
    public static final Individual GuestRoom_3 = m_model.createIndividual( "http://www.owl-ontologies.com/Travel.owl#GuestRoom_3", GuestRoom );
    
    public static final Individual HotelReservation_5 = m_model.createIndividual( "http://www.owl-ontologies.com/Travel.owl#HotelReservation_5", HotelReservation );
    
    public static final Individual Hotel_1 = m_model.createIndividual( "http://www.owl-ontologies.com/Travel.owl#Hotel_1", Hotel );
    
    public static final Individual Hotel_2 = m_model.createIndividual( "http://www.owl-ontologies.com/Travel.owl#Hotel_2", Hotel );
    
    public static final Individual Msg_HotelReservationNotifyRQ_4 = m_model.createIndividual( "http://www.owl-ontologies.com/Travel.owl#Msg_HotelReservationNotifyRQ_4", Msg_HotelViewDetailServiceRQ );
    
    public static final Individual PaymentMethod_6 = m_model.createIndividual( "http://www.owl-ontologies.com/Travel.owl#PaymentMethod_6", PaymentMethod );
    
    public static final Individual RQ1 = m_model.createIndividual( "http://www.owl-ontologies.com/Travel.owl#RQ1", Msg_HotelAlterServiceRQ );
    
    public static final Individual RQ2 = m_model.createIndividual( "http://www.owl-ontologies.com/Travel.owl#RQ2", Msg_HotelAlterServiceRQ );
    
    public static final Individual RS1 = m_model.createIndividual( "http://www.owl-ontologies.com/Travel.owl#RS1", Msg_HotelAlterBookedServiceRQ );
    
    public static final Individual RS2 = m_model.createIndividual( "http://www.owl-ontologies.com/Travel.owl#RS2", Msg_HotelAlterBookedServiceRQ );
    
}
